# for Fujitsu Compiler on ARM
set(CMAKE_C_COMPILER "mpifccpx" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "-Nclang -DNDEBUG -Ofast" CACHE STRING "" FORCE)
set(OpenMP_C_FLAGS "-fopenmp" CACHE STRING "" FORCE)
set(CMAKE_Fortran_COMPILER "mpifrtpx" CACHE STRING "" FORCE)
set(CMAKE_Fortran_FLAGS_RELEASE "-DNDEBUG -DFUJITSU -Kfast" CACHE STRING "" FORCE)
set(OpenMP_Fortran_FLAGS "-Kopenmp" CACHE STRING "" FORCE)

# for SSL2
set(BLAS_LIBRARIES "-SSL2MPI -SSL2BLAMP" CACHE STRING "" FORCE)
set(LAPACK_LIBRARIES ${BLAS_LIBRARIES} CACHE STRING "" FORCE)


# ScaLAPACK
if(USE_SCALAPACK)
  if(SCALAPACK_LIBRARIES MATCHES "")
    set(SCALAPACK_LIBRARIES "-lscalapacksve -lmpi_usempi_ignore_tkr -lmpi_mpifh")
  endif(SCALAPACK_LIBRARIES MATCHES "")
  message(STATUS "SCALAPACK_LIBRARIES is ${SCALAPACK_LIBRARIES}")
endif(USE_SCALAPACK)
